### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by briceparent** [leandigo/pyoneall#2]
Is this project (and Django-oneall) still maintained and/or used?
It seems it hasn't gotten any update in 3 years, and since, the write-to-users-wall endpoints has been deprecated in favour of the Push API.
Does anyone still use it? In production?
Thanks

**Comment by Liz4v** [comment]
I'm not entirely sure, but I don't think any of the current maintainers still use it. I don't.

I'll gladly review API updates though.

**Comment by briceparent** [comment]
Thanks!
Anyway, I've not yet chosen neither the solution (like OneAll) nor the integration (like this lib). I'm just looking around for what already exists and works, not to reinvent the wheel.
So don't lose any time on my request, it was really just a message to have an idea if I should or not take this project into account.
Brice

**Comment by Liz4v** [comment]
Closing because the question is answered.
